### ISSUE TITLE
Ruby 2.7 Deprecations

### ISSUE THREAD

**Issue by SlaunchaMan** [CocoaPods/Nanaimo#49]
Ruby 2.7 begins [a transition](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) with positional and keyword arguments for Ruby 3; this library now generates some warnings at runtime:

```
/Users/jeff/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nanaimo-0.2.6/lib/nanaimo/writer/pbxproj.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/jeff/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nanaimo-0.2.6/lib/nanaimo/writer.rb:35: warning: The called method `initialize' is defined here
```

**Comment by dnkoutso** [comment]
Fixed here https://github.com/CocoaPods/Nanaimo/pull/53
