### ISSUE TITLE
Cut a new release 

### ISSUE THREAD

**Issue by byohay** [CocoaPods/Nanaimo#61]
Hi,

I'm the maintainer of [Kintsugi](https://github.com/Lightricks/Kintsugi/), a tool for solving Git conflicts in pbxproj files. It uses XcodeProj to read and write the project files which internally uses Nanaimo. Some users encountered issues where some strings were quoted and according to Xcode they shouldn't be quoted (It was fixed in https://github.com/CocoaPods/Nanaimo/pull/58). 
Is it possible to cut a release soon so Kintsugi will write projects in a way that's consistent with how Xcode writes them?
Thanks!

**Comment by arthuralee** [comment]
@segiddins any chance you could help cut a release? Just tagging you since you merged the PR. thank you 🙂

**Comment by arthuralee** [comment]
@segiddins @dnkoutso ping

**Comment by arthuralee** [comment]
@segiddins ping again, this is a papercut we run into often when using cocoapods so i would love to see it incorporated into future cocoapods releases.

also pinging other active cocoapods manitainers @orta @amorde

**Comment by amorde** [comment]
Released [0.4.0](https://github.com/CocoaPods/Nanaimo/releases/tag/0.4.0)
